---

- name: "Create Kafka topics"
  include: kafka_manage.yml
  vars:
    command_args: "kafka-topics --zookeeper {{ groups['cp_zookeeper_nodes'][0] }}:2181 --create --topic {{ item.name }} --partitions {{ item.partitions }} --replication-factor {{ item.replication_factor }} --if-not-exists"
  loop: "{{ topics | flatten(levels=1) }}"

# TODO: Continue here
- name: "Create Cassandra tables"

- name: "Create Kafka connectors"

- name: "Start Kafka connectors"


