---
docker:
  host:
    base_folder: "{{cassandra.base_folder}}"
    exposed_folders :
      log: "{{cassandra.base_folder}}/log"
      conf: "{{cassandra.base_folder}}/conf"
      data_sstables: "{{cassandra.base_folder}}/datafile"
      data_commitlog: "{{cassandra.base_folder}}/commitlog"
      data_cdc: "{{cassandra.base_folder}}/cdc"
      data_saved_caches: "{{cassandra.base_folder}}/saved_caches"
      data_hints: "{{cassandra.base_folder}}/hints"
  container:
    base_folder: "/opt/cassandra"
    exposed_folders:
      log: "/opt/cassandra/log"
      conf: "/opt/cassandra/conf"
      data_sstables: "/opt/cassandra/datafile"
      data_commitlog: "/opt/cassandra/commitlog"
      data_cdc: "/opt/cassandra/cdc"
      data_saved_caches: "/opt/cassandra/saved_caches"
      data_hints: "/opt/cassandra/hints"