---
- name: "Prepare environment for hadoop instance"
  include_role:
    name: hadoop-common
  vars:
    docker_command: "{{hadoop.container.install_folder}}/sbin/hadoop-daemon.sh start namenode > {{hadoop.container.exposed_folder.log}}/hdfs-namenode-start.log"

- name: "Format hdfs partion"
  become: yes
  shell: docker exec hadoop-hdfs-namenode bash -l -c '{{hadoop.container.install_folder}}/bin/hdfs namenode -format -force  hadoop-hdfs > {{hadoop.container.exposed_folder.log}}/hdfs-format.log'
  when:
    - (pristine_instance | bool) and (not (absent_from_node | bool))


