---
- name: "Pull image {{ docker_image }} and (re)start container with name 'cp-schema-registry-{{ node_id }}'"
  become: yes
  docker_container:
    name: "cp-schema-registry"
    hostname: "cp-schema-registry"
    state: started
    pull: true
    restart: yes
    image: "{{ docker_image }}"
    ports:
      - "18081:18081"
    network_mode: host
    cpu_quota: "5000"
    cpu_period: "80000"
    memory: "768M"
    env:
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "{{ groups['cp_zookeeper_nodes'] | join(':2181,')}}:2181"
      SCHEMA_REGISTRY_HOST_NAME: "{{ inventory_hostname }}"
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:18081"
      SCHEMA_REGISTRY_DEBUG: "true"
    restart_policy: always
    tty: yes
