---
- name: "Prepare environment for docker instance"
  include_role:
    name: docker-pre-image

- name: "Pull image {{ docker_image }} and (re)start container with name {{ docker_instance_name }}"
  become: true
  docker_container:
    name: "{{ docker_instance_name }}"
    hostname: "{{ docker_instance_name }}"
    state: started
    pull: true
    restart: yes
    image: "{{ docker_image }}"
    #user: "{{ ansible_real_user_id }}:{{ ansible_real_group_id }}"
    volumes:
      - "{{ host_data_folders.log_folder }}:/var/lib/zookeeper/log"
      - "{{ host_data_folders.data_folder }}:/var/lib/zookeeper/data"
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    network_mode: host
    cpu_quota: "10000"
    cpu_period: "80000"
    memory: "2G"
    env:
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_SERVER_ID: "{{ node_id | string }}"
      ZOOKEEPER_TICK_TIME: "2000" # Millis
      ZOOKEEPER_INIT_LIMIT: "5" # Ticks
      ZOOKEEPER_SYNC_LIMIT: "2" # Ticks
      ZOOKEEPER_SERVERS: "{{ groups['cp_zookeeper_nodes'] | join(':2888:3888;')}}:2888:3888"
    restart_policy: always
    tty: yes
  when: not (absent_from_node | bool)
