---
# This role sets up a user for the cluster configuration and sets up the ssh accesses
 
- name: "Create {{ cluster_config_user }} user"
  become: yes
  user:
    name: "{{ cluster_config_user }}"
    comment: "Cluster configuration account"
    generate_ssh_key: yes
  when: false

- name: "Enable pasword-less sudo for user panda-config"
  become: yes
  lineinfile: dest=/etc/sudoers
              regexp="^{{ cluster_config_user }} ALL=(ALL) NOPASSWD:ALL"
              line="{{ cluster_config_user }} ALL=(ALL) NOPASSWD:ALL"
              state=present
  when: false

- name: "Register ssh autorized_keys into {{ cluster_config_user }}"
  become: yes
  authorized_key:
    user: "{{ cluster_config_user }}"
    state: present
    key: '{{ item }}'
  with_lines: cat '{{ authorized_keys_folder }}'
  when: false


#^127\.0\.1\.1(( |\t)*)((?!\b\.digitalpanda\.org\b).)*$
- name: "Check domain name {{ cluster_config_domain_name }} present"
  become: yes
  replace: dest=/etc/hosts
           regexp='^(127\.0\.1\.1(( |\t)+)((?!\b\.{{ cluster_config_domain_name }}\b).)+)$'
           replace='\1 {{ ansible_hostname }}.{{ cluster_config_domain_name }}'