---

- name: "Build and push 'cassandra' docker image"
  become: yes
  docker_image:
    path: "{{ docker_images }}/cassandra"
    name: "{{ docker_registry.fqdn }}:{{ docker_registry.port }}/cassandra"
    tag: latest
    push: yes
