---
#TODO:1) fix frontend build and deploy ; 2) container processes should have dedicated users

- hosts: x64-build-node
  roles:
    - { role: docker-registry,
        required_containers: ['digitalpanda-backend'] ,
        when: build_code}
  tags:
    - wip

- hosts: cassandra-nodes
  roles:
   - cassandra

- hosts: backends
  roles:
    - digitalpanda-backend
  tags:
    - wip

- hosts: cassandra-test-data-injector
  roles:
    - test-data-injector


  #- hosts: frontends
  #roles:
  #  - digitalpanda-frontend




