---
- hosts: x64-build-node
  roles:
    - { role: docker-registry,
        required_containers: ['cassandra'] ,
        when: build_code}

- hosts:
    - cassandra-nodes
    - backends
    - frontends
  roles:
    - digitalpanda-base

- hosts: cassandra-nodes
  roles:
   - cassandra

- hosts: backends
  roles:
    - digitalpanda-backend

- hosts: cassandra-test-data-injector
  roles:
  - { role: test-data-injector,
      when: inject_test_data}

- hosts: frontends
  roles:
    - digitalpanda-frontend




