---
## Setup and start a spark using : docker, hypriot, raspberry-pi-3-b:workers, x64:master

- hosts: hadoop_master_node hadoop_worker_nodes
  roles:
   - { role: "hadoop-common", clear_cluster: true}

- hosts: hadoop-master-node
  roles:
    - hadoop-hdfs-namenode
    - hadoop-yarn-resourcemanager

- hosts: hadoop-worker-nodes
  roles:
    - hadoop-yarn-nodemanager
    - hadoop-hdfs-datanode



