---
# This role sets up machine as network bridge based on an internal and external interface

- name: Copy "interfaces" file for bridging
  become: yes
  template:
    src: ./templates/interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    mode: "u=rw,g=r,o=r"

- name: Copy static host name resolution file
  become: yes
  template:
    src: ./templates/hosts.j2
    dest: /etc/hosts
    owner: root
    mode: "u=rw,g=r,o=r"

- name: "Enable dns server update"
  become: yes
  shell: chattr -i /etc/resolv.conf
  when: internal_dns

- name: "Set internal DNS server ip"
  become: yes
  template:
    src: ./templates/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    mode: "u=rw,g=r,o=r"
  when: internal_dns

- name: "Disable dns server update"
  become: yes
  shell: chattr +i /etc/resolv.conf
  when: internal_dns

- name: Copy iptables script for bridging
  become: yes
  template:
    src: ./templates/enable_bridge_iptables.sh.j2
    dest: /opt/enable_bridge_iptables.sh
    mode: "u=rwx,g=rx,o=rx"

- name: Execute iptables bridging script at each startup
  become: yes
  lineinfile: dest=/etc/rc.local
              regexp="exit 0|enable_bridge_iptable"
              line="/opt/enable_bridge_iptables.sh || true"
              state=present