---

- name: "Pull backend code from {{ backend_repo.clone_url }}"
  git:
    repo: "{{ backend_repo.clone_url }}"
    dest: "{{ backend_repo.target_path }}"

- name: "Build backend and copy jar into docker folder"
  shell: {{ backend_repo.host_path }}/scripts/build.sh

- name: "Build and push 'digitalpanda-backend' docker image"
  become: yes
  docker_image:
    path: "{{ docker_images }}/backend-java"
    name: "{{ docker_registry.fqdn }}:{{ docker_registry.port }}/digitalpanda-backend"
    tag: latest
    push: yes
