---
- set_fact:
    docker_image: "{{ docker_registry.fqdn }}:{{ docker_registry.port }}/{% if ansible_architecture == 'x86_64' %}hadoop{% else %}hadoop-arm{% endif %}:{{ apache_hadoop.version }}"

- name: "Prepare environment for docker instance"
  include_role:
    name: docker-pre-image

- name: "Add hadoop global configuration files on host"
  template:
    src: "{{ item }}.j2"
    dest: "{{ host_data_folders.config }}/{{ item }}"
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - yarn-site.xml
    - capacity-scheduler.xml

- name: "Pull image {{ docker_image }} and (re)start container with name {{ docker_instance_name }}-* "
  become: yes
  docker_container:
    name: "{{ docker_instance_name }}"
    state: started
    pull: true
    command: "{{ docker_command }}"
    restart: yes
    image: "{{ docker_image }}"
    volumes:
      - "{{ host_base_folder }}:{{ hadoop.container.exposed_folder.base }}"
    network_mode: host
    restart_policy: always
    tty: yes
  when: docker_instance_name | length > 0
