---
- set_fact:
    docker_image: "{{ docker_registry.fqdn }}:{{ docker_registry.port }}/{% if ansible_architecture == 'x86_64' %}hadoop{% else %}hadoop-arm{% endif %}:latest"
  when: hadoop_container_name != ""

- name: "Prepare environment for docker instance"
  include_role:
    name: docker-pre-image

- name: "Add hadoop global configuration files on host"
  template:
    src: "{{ item }}.j2"
    dest: "{{ hadoop.host.exposed_folder.config }}/{{ item }}"
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - yarn-site.xml
  when: (pristine_instance | bool) or (absent_from_node | bool)

- name: "Pull image {{ docker_image }} and (re)start container with name {{ hadoop_container_name }}-* "
  become: yes
  docker_container:
    name: "{{ hadoop_container_name }}"
    state: started
    restart: yes
    image: "{{ docker_image }}"
    volumes:
      - "{{ host_data_folders }}:{{ hadoop.container.exposed_folder.base }}"
    network_mode: host
    restart_policy: always
    tty: yes
  when: hadoop_container_name != ""
